#!/bin/bash



#### note : no spaces alowed here :w
#### run current script you can do map command :
#     :map <C-t> :!./%<cr>
# :! run bash command  ./ run in current folder % current file <cr> carett return :w
 


echo "hello there , $1!"


################# IF 
num=10 



if [ $num = 10 ];
then 

	echo da
else 
	echo  net 

fi
#####################################



name="alexa" 



if [ $name = "alex" ];
then 
 
	echo "hello $name !!"

elif [ $name = "ssss" ] 
then
	echo "jopa"

else 
	echo  net 

fi

########################################case


case $1 in

	init)
		echo "init"
	;;

	test) 
		echo "nahon"
	;;


	*)
		echo "else"
	;;


esac

############################################### file exist 

file="./bash_script"

if [ -f $file  ] #### -d for directory || check  f or exists use -e 
then 
	echo "true "
else
	echo "false "
fi

