set guifont=Incosolata\ for\ Powerline
set encoding=utf-8
let g:Powerline_symbols = 'fancy'
set laststatus=2
set fillchars+=stl:\ ,stlnc:\
set t_Co=256
set term=xterm-256color
let g:airline_powerline_fonts=1
let g:Powerline_symbols='unicode'
set termencoding=utf-8
